package org.example.videoclub.models.assist;

public enum EPais {

    // (Banderas y códigos) https://es-academic.com/dic.nsf/eswiki/591762

//    Andorra("AND", "Andorra"),
//    EmiratosArabesUnidos("ARE", "Emiratos Árabes Unidos"),
//    Afganistan("AFG", "Afganistán"),
//    AntiguaYBarbuda("ATG", "Antigua y Barbuda"),
//    Anguila("AIA", "Anguila"),
//    Albania("ALB", "Albania"),
//    Armenia("ARM", "Armenia"),
//    AntillasNeerlandesas("ANT", "Antillas Neerlandesas"),
//    Angola("AGO", "Angola"),
//    Antartida("ATA", "Antártida"),
    Argentina("ARG", "Argentina"),
//    SamoaAmericana("ASM", "Samoa Americana"),
//    Austria("AUT", "Austria"),
//    Australia("AUS", "Australia"),
//    Aruba("ABW", "Aruba"),
//    IslasAland("ALA", "Islas Áland"),
//    Azerbaiyan("AZE", "Azerbaiyán"),
//    BosniaYHerzegovina("BIH", "Bosnia y Herzegovina"),
//    Barbados("BRB", "Barbados"),
//    Bangladesh("BGD", "Bangladesh"),
//    Belgica("BEL", "Bélgica"),
//    BurkinaFaso("BFA", "Burkina Faso"),
//    Bulgaria("BGR", "Bulgaria"),
//    Bahrein("BHR", "Bahréin"),
//    Burundi("BDI", "Burundi"),
//    Benin("BEN", "Benin"),
//    SanBartolome("BLM", "San Bartolomé"),
//    Bermudas("BMU", "Bermudas"),
//    Brunei("BRN", "Brunéi"),
//    Bolivia("BOL", "Bolivia"),
    Brasil("BRA", "Brasil"),
//    Bahamas("BHS", "Bahamas"),
//    Bhutan("BTN", "Bhután"),
//    IslaBouvet("BVT", "Isla Bouvet"),
//    Botsuana("BWA", "Botsuana"),
//    Belarus("BLR", "Belarús"),
//    Belice("BLZ", "Belice"),
//    Canada("CAN", "Canadá"),
//    IslasCocos("CCK", "Islas Cocos"),
//    RepublicaCentroAfricana("CAF", "República Centro-Africana"),
//    Congo("COG", "Congo"),
//    Suiza("CHE", "Suiza"),
//    CostaEeMarfil("CIV", "Costa de Marfil"),
//    IslasCook("COK", "Islas Cook"),
//    Chile("CHL", "Chile"),
//    Camerun("CMR", "Camerún"),
//    China("CHN", "China"),
//    Colombia("COL", "Colombia"),
//    CostaRica("CRI", "Costa Rica"),
//    Cuba("CUB", "Cuba"),
//    CaboVerde("CPV", "Cabo Verde"),
//    IslasChristmas("CXR", "Islas Christmas"),
//    Chipre("CYP", "Chipre"),
//    RepublicaCheca("CZE", "República Checa"),
    Alemania("DEU", "Alemania"),
//    Yibuti("DJI", "Yibuti"),
    Dinamarca("DNK", "Dinamarca"),
//    Dominica("DMA", "Domínica"),
//    RepublicaDominicana("DOM", "República Dominicana"),
//    Argel("DZA", "Argel"),
//    Ecuador("ECU", "Ecuador"),
//    Estonia("EST", "Estonia"),
//    Egipto("EGY", "Egipto"),
//    SaharaOccidental("ESH", "Sahara Occidental"),
//    Eritrea("ERI", "Eritrea"),
    Espana("ESP", "España"),
//    Etiopia("ETH", "Etiopía"),
//    Finlandia("FIN", "Finlandia"),
//    Fiji("FJI", "Fiji"),
//    IslasMalvinas("KLK", "Islas Malvinas"),
//    Micronesia("FSM", "Micronesia"),
//    IslasFaroe("FRO", "Islas Faroe"),
    Francia("FRA", "Francia"),
//    Gabon("GAB", "Gabón"),
    ReinoUnido("GBR", "Reino Unido"),
//    Granada("GRD", "Granada"),
//    Georgia("GEO", "Georgia"),
//    GuayanaFrancesa("GUF", "Guayana Francesa"),
//    Guernsey("GGY", "Guernsey"),
//    Ghana("GHA", "Ghana"),
//    Gibraltar("GIB", "Gibraltar"),
//    Groenlandia("GRL", "Groenlandia"),
//    Gambia("GMB", "Gambia"),
//    Guinea("GIN", "Guinea"),
//    Guadalupe("GLP", "Guadalupe"),
//    GuineaEcuatorial("GNQ", "Guinea Ecuatorial"),
//    Grecia("GRC", "Grecia"),
//    GeorgiaDelSurEIslasSandwichDelSur("SGS", "Georgia del Sur e Islas Sandwich del Sur"),
//    Guatemala("GTM", "Guatemala"),
//    Guam("GUM", "Guam"),
//    GuineaBissau("GNB", "Guinea-Bissau"),
//    Guayana("GUY", "Guayana"),
//    HongKong("HKG", "Hong Kong"),
//    IslasHeardYMcDonald("HMD", "Islas Heard y McDonald"),
//    Honduras("HND", "Honduras"),
//    Croacia("HRV", "Croacia"),
//    Haiti("HTI", "Haití"),
//    Hungria("HUN", "Hungría"),
//    Indonesia("IDN", "Indonesia"),
    Irlanda("IRL", "Irlanda"),
//    Israel("ISR", "Israel"),
//    IslaDeMan("IMN", "Isla de Man"),
    India("IND", "India"),
//    TerritorioBritanicoDelOceanoIndico("IOT", "Territorio Británico del Océano Índico"),
//    Irak("IRQ", "Irak"),
//    Iran("IRN", "Irán"),
//    Islandia("ISL", "Islandia"),
    Italia("ITA", "Italia"),
//    Jersey("JEY", "Jersey"),
//    Jamaica("JAM", "Jamaica"),
//    Jordania("JOR", "Jordania"),
    Japon("JPN", "Japón"),
//    Kenia("KEN", "Kenia"),
//    Kirguistan("KGZ", "Kirguistán"),
//    Camboya("KHM", "Camboya"),
//    Kiribati("KIR", "Kiribati"),
//    Comoros("COM", "Comoros"),
//    SanCristobalYNieves("KNA", "San Cristóbal y Nieves"),
//    CoreaDelNorte("PRK", "Corea del Norte"),
//    CoreaDelSur("KOR", "Corea del Sur"),
//    Kuwait("KWT", "Kuwait"),
//    IslasCaiman("CYM", "Islas Caimán"),
//    Kazajstan("KAZ", "Kazajstán"),
//    Laos("LAO", "Laos"),
//    Libano("LBN", "Líbano"),
//    SantaLucia("LCA", "Santa Lucía"),
//    Liechtenstein("LIE", "Liechtenstein"),
//    SriLanka("LKA", "Sri Lanka"),
//    Liberia("LBR", "Liberia"),
//    Lesotho("LSO", "Lesotho"),
//    Lituania("LTU", "Lituania"),
//    Luxemburgo("LUX", "Luxemburgo"),
//    Letonia("LVA", "Letonia"),
//    Libia("LBY", "Libia"),
//    Marruecos("MAR", "Marruecos"),
//    Monaco("MCO", "Mónaco"),
//    Moldova("MDA", "Moldova"),
//    Montenegro("MNE", "Montenegro"),
//    Madagascar("MDG", "Madagascar"),
//    IslasMarshall("MHL", "Islas Marshall"),
//    Macedonia("MKD", "Macedonia"),
//    Mali("MLI", "Mali"),
//    Myanmar("MMR", "Myanmar"),
//    Mongolia("MNG", "Mongolia"),
//    Macao("MAC", "Macao"),
//    Martinica("MTQ", "Martinica"),
//    Mauritania("MRT", "Mauritania"),
//    Montserrat("MSR", "Montserrat"),
//    Malta("MLT", "Malta"),
//    Mauricio("MUS", "Mauricio"),
//    Maldivas("MDV", "Maldivas"),
//    Malawi("MWI", "Malawi"),
    Mexico("MEX", "México"),
//    Malasia("MYS", "Malasia"),
//    Mozambique("MOZ", "Mozambique"),
//    Namibia("NAM", "Namibia"),
//    NuevaCaledonia("NCL", "Nueva Caledonia"),
//    Niger("NER", "Níger"),
//    IslasNorkfolk("NFK", "Islas Norkfolk"),
//    Nigeria("NGA", "Nigeria"),
//    Nicaragua("NIC", "Nicaragua"),
//    PaisesBajos("NLD", "Países Bajos"),
//    Noruega("NOR", "Noruega"),
//    Nepal("NPL", "Nepal"),
//    Nauru("NRU", "Nauru"),
//    Niue("NIU", "Niue"),
    NuevaZelanda("NZL", "Nueva Zelanda"),
//    Oman("OMN", "Omán"),
//    Panama("PAN", "Panamá"),
//    Peru("PER", "Perú"),
//    PolinesiaFrancesa("PYF", "Polinesia Francesa"),
//    PapuaNuevaGuinea("PNG", "Papúa Nueva Guinea"),
//    Filipinas("PHL", "Filipinas"),
//    Pakistan("PAK", "Pakistán"),
//    Polonia("POL", "Polonia"),
//    SanPedroYMiquelon("SPM", "San Pedro y Miquelón"),
//    IslasPitcairn("PCN", "Islas Pitcairn"),
//    PuertoRico("PRI", "Puerto Rico"),
//    Palestina("PSE", "Palestina"),
//    Portugal("PRT", "Portugal"),
//    IslasPalaos("PLW", "Islas Palaos"),
//    Paraguay("PRY", "Paraguay"),
//    Qatar("QAT", "Qatar"),
//    Reunion("REU", "Reunión"),
//    Rumania("ROU", "Rumanía"),
//    SerbiaYMontenegro("SRB", "Serbia y Montenegro"),
//    Rusia("RUS", "Rusia"),
//    Ruanda("RWA", "Ruanda"),
//    ArabiaSaudita("SAU", "Arabia Saudita"),
//    IslasSolomon("SLB", "Islas Solomón"),
//    Seychelles("SYC", "Seychelles"),
//    Sudan("SDN", "Sudán"),
//    Suecia("SWE", "Suecia"),
//    Singapur("SGP", "Singapur"),
//    SantaElena("SHN", "Santa Elena"),
//    Eslovenia("SVN", "Eslovenia"),
//    IslasSvalbardYJanMayen("SJM", "Islas Svalbard y Jan Mayen"),
//    Eslovaquia("SVK", "Eslovaquia"),
//    SierraLeona("SLE", "Sierra Leona"),
//    SanMarino("SMR", "San Marino"),
//    Senegal("SEN", "Senegal"),
//    Somalia("SOM", "Somalia"),
//    Surinam("SUR", "Surinam"),
//    SantoTomeYPrincipe("STP", "Santo Tomé y Príncipe"),
//    ElSalvador("SLV", "El Salvador"),
//    Siria("SYR", "Siria"),
//    Suazilandia("SWZ", "Suazilandia"),
//    IslasTurcasYCaicos("TCA", "Islas Turcas y Caicos"),
//    Chad("TCD", "Chad"),
//    TerritoriosAustralesFranceses("ATF", "Territorios Australes Franceses"),
//    Togo("TGO", "Togo"),
//    Tailandia("THA", "Tailandia"),
//    Tanzania("TZA", "Tanzania"),
//    Tayikistan("TJK", "Tayikistán"),
//    Tokelau("TKL", "Tokelau"),
//    TimorLeste("TLS", "Timor-Leste"),
//    Turkmenistan("TKM", "Turkmenistán"),
//    Tunez("TUN", "Túnez"),
//    Tonga("TON", "Tonga"),
//    Turquia("TUR", "Turquía"),
//    TrinidadYTobago("TTO", "Trinidad y Tobago"),
//    Tuvalu("TUV", "Tuvalu"),
//    Taiwan("TWN", "Taiwán"),
//    Ucrania("UKR", "Ucrania"),
//    Uganda("UGA", "Uganda"),
    EstadosUnidosDeAmerica("USA", "Estados Unidos de América"),
//    Uruguay("URY", "Uruguay"),
//    Uzbekistan("UZB", "Uzbekistán"),
//    CiudadDelVaticano("VAT", "Ciudad del Vaticano"),
//    SanVicenteYLasGranadinas("VCT", "San Vicente y las Granadinas"),
//    Venezuela("VEN", "Venezuela"),
//    IslasVirgenesBritanicas("VGB", "Islas Vírgenes Británicas"),
//    IslasVirgenesDeLosEstadosUnidosDeAmerica("VIR", "Islas Vírgenes de los Estados Unidos de América"),
//    Vietnam("VNM", "Vietnam"),
//    Vanuatu("VUT", "Vanuatu"),
//    WallisYFutuna("WLF", "Wallis y Futuna"),
//    Samoa("WSM", "Samoa"),
//    Yemen("YEM", "Yemen"),
//    Mayotte("MYT", "Mayotte"),
//    Sudafrica("ZAF", "Sudáfrica"),
    ;

    private final String codigo;
    private final String nombre;

    EPais(String codigo, String nombre) {
        this.codigo = codigo;
        this.nombre = nombre;
    }

    public String getCodigo() {
        return codigo;
    }

    public String getNombre() {
        return nombre;
    }

}
